# Generated by Django 3.1.3 on 2020-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='adress', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='email@gail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='name', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(default=1),
        ),
    ]
